### ISSUE TITLE
Error on getStats

### ISSUE THREAD

**Issue by georgeoftown** [sirCamp/Xenapi#1]
On class [XenVirtualMachine](https://github.com/sirCamp/Xenapi/blob/master/src/Sircamp/Xenapi/Element/XenVirtualMachine.php)

At line [362](https://github.com/sirCamp/Xenapi/blob/master/src/Sircamp/Xenapi/Element/XenVirtualMachine.php#L362) yo try to call VMGetUUID and this function is getUUID() on line [273](https://github.com/sirCamp/Xenapi/blob/master/src/Sircamp/Xenapi/Element/XenVirtualMachine.php#L273)

Sorry for my english

**Comment by sirCamp** [comment]
Thanks I'll resolved it asap

**Comment by sirCamp** [comment]
I've fixed the issue, and correct the method.
You will find it on version _2.1_
Thanks!
