### ISSUE TITLE
Errors with respect/validation dependecies   in php7.0

### ISSUE THREAD

**Issue by raj-24x7** [sirCamp/Xenapi#7]
the XenAPI does not work with latest php7.0 . has some issues with dependencies in respect/validator
 Respect\Validation\Exceptions\ComponentException: "string" is not a valid rule in /var/www/html/project/vendor/respect/validation/library/Validator.php on line 236 @sirCamp

**Comment by colq2** [comment]
I created a pull request that fixed this problem. Hopefully this will merged soon.

**Comment by sirCamp** [comment]
@colq2 your pull request has been merged! thanks ;)
